version: '3'

services:
  locations-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: locations
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MYSQL_USER: locations
      MYSQL_PASSWORD: locations

  locations-app:
    image: training360/locations
    restart: always
    depends_on:
      - locations-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://locations-mariadb:3306/locations'
    entrypoint: ["./wait-for-it.sh", "-t", "120", "locations-mariadb:3306", "--", "java", "org.springframework.boot.loader.JarLauncher"]
    expose:
      - 8080
    scale: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - locations-app
    ports:
      - "8081:8081"